name: Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.6

      - name: Install Node.js
        uses: actions/setup-node@v6.4.0
        with:
          cache: pnpm
          node-version: 22

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint
        env:
          NTP_API_KEY: ${{ secrets.NTP_API_KEY }}
          NTP_API_URL: ${{ secrets.NTP_API_URL }}
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
